# Generated by Django 5.1.7 on 2025-04-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='intro_offer_redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
