# Generated by Django 5.1.7 on 2025-03-28 16:19

import django.db.models.deletion
import images.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=images.models.get_image_path)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to=images.models.get_image_path)),
                ('is_paid', models.BooleanField(default=False)),
                ('download_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated Image',
                'verbose_name_plural': 'Generated Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
