# Generated by Django 5.1.7 on 2025-04-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_generatedimage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StylePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_key', models.CharField(max_length=50, unique=True)),
                ('prompt', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Style Prompt',
                'verbose_name_plural': 'Style Prompts',
            },
        ),
    ]
