# Generated by Django 5.1.7 on 2025-03-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='upi_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='upi_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verification_method',
            field=models.CharField(blank=True, choices=[('transaction_id', 'Transaction ID'), ('screenshot', 'Screenshot')], max_length=20, null=True),
        ),
    ]
