# Generated by Django 5.1.7 on 2025-04-06 07:30

import config.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentverificationattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, storage=config.storage.PaymentScreenshotsStorage(), upload_to='payment_screenshots/'),
        ),
    ]
