# Generated by Django 5.1.7 on 2025-04-15 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentverificationattempt',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymentverificationattempt',
            name='user',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_id',
            new_name='dodo_payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='upi_id',
            new_name='order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reference_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='upi_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='verification_method',
        ),
        migrations.AddField(
            model_name='payment',
            name='dodo_payment_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='dodo_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='credits_purchased',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PaymentSession',
        ),
        migrations.DeleteModel(
            name='PaymentVerificationAttempt',
        ),
    ]
