# Generated by Django 5.1.7 on 2025-04-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_paymentverificationattempt_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='region',
            field=models.CharField(choices=[('IN', 'India'), ('GLOBAL', 'Global')], default='IN', max_length=10),
        ),
    ]
