# Generated by Django 5.1.7 on 2025-04-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_pricingplan_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='is_intro_offer',
            field=models.BooleanField(default=False),
        ),
    ]
